version: 0.2

phases:
  pre_build:
    commands:
      - printenv
  build:
    commands:
      - docker build -t jenkins-pipeline-test:latest .
      - docker build -t jenkins-pipeline-test:test -f Dockerfile-Test .
      - docker run --rm jenkins-pipeline-test:test